version: '2'
services:
  beers-service:
    container_name: beers-service
    build:
      dockerfile: Dockerfile
    image: beers-service:latest
    ports:
      - 8080:8080
    networks:
      - beers-network
networks:
  beers-network:
    driver: bridge